---
name: Modwheel
version: 0.3.3
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Tree-based Web framework.
license: perl
resources:
  Download: http://search.cpan.org/~asksh/Modwheel-0.3.3/
  HomePage: http://www.0x61736b.net/Modwheel
  license: http://dev.perl.org/licenses/
requires:
  AppConfig: 1.56
  DBI: 1.51
  Digest::SHA1: 2.07
  Getopt::Euclid: 0.001
  HTML::Parser: 3.48
  HTML::Tagset: 3.03
  IO::Interactive: 0.0.1
  IO::Prompt: 0.099004
  JSON::Syck: 0.14
  List::MoreUtils: 0.13
  List::Util: 1.15
  Params::Util: 0.22
  Perl6::Export: 0.06
  Perl6::Export::Attrs: 0.0.1
  Perl6::Form: 0.04
  Readonly: 1.03
  Scalar::Util: 1.14
  Sub::Install: 0.9
  Template: 2.17
  Template::Stash::XS: 0
  Term::ReadKey: 2.3
  UNIVERSAL::require: 0.1
  URI: 1.29
  YAML: 0.5
  YAML::Syck: 0.7
  namespace::clean: 0.01
  version: 0
build_requires:
  Test::Simple: 0.42
recommends:
  Crypt::Eksblowfish: 0.001
  Crypt::UnixCrypt: 1
  Digest::MD5: 2.35
  Digest::SHA1: 2.04
  Perl::Critic: 1.051
  Pod::Coverage: 0.18
  Readonly::XS: 1.02
  Test::Exception: 0.25
  Test::Kwalitee: 0.3
  Test::Perl::Critic: 1
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
  Test::YAML::Meta: 0.04
  Test::YAML::Valid: 0.03
  UNIVERSAL::require: 0.11
dynamic_config: 0
provides:
  Class::InsideOut::Policy::Modwheel:
    file: lib/Class/InsideOut/Policy/Modwheel.pm
    version: 1.06
  Modwheel:
    file: lib/Modwheel.pm
    version: 0.3.3
  Modwheel::Configure:
    file: lib/Modwheel/Configure.pm
    version: 0.3.3
  Modwheel::Crypt:
    file: lib/Modwheel/Crypt.pm
    version: 0.3.3
  Modwheel::Crypt::Base:
    file: lib/Modwheel/Crypt/Base.pm
    version: 0.2.3
  Modwheel::Crypt::Eksblowfish:
    file: lib/Modwheel/Crypt/Eksblowfish.pm
    version: 0.2.3
  Modwheel::Crypt::PLAINTEXT:
    file: lib/Modwheel/Crypt/PLAINTEXT.pm
    version: 0.2.3
  Modwheel::Crypt::SHA1:
    file: lib/Modwheel/Crypt/SHA1.pm
    version: 0.2.3
  Modwheel::Crypt::UnixCrypt:
    file: lib/Modwheel/Crypt/UnixCrypt.pm
    version: 0.2.3
  Modwheel::DB:
    file: lib/Modwheel/DB.pm
    version: 0.3.3
  Modwheel::DB::Base:
    file: lib/Modwheel/DB/Base.pm
    version: 0.3.3
  Modwheel::DB::MySQL:
    file: lib/Modwheel/DB/MySQL.pm
    version: 0.3.3
  Modwheel::DB::PostgreSQL:
    file: lib/Modwheel/DB/PostgreSQL.pm
    version: 0.3.3
  Modwheel::DB::SQLite:
    file: lib/Modwheel/DB/SQLite.pm
    version: 0.3.3
  Modwheel::DB::SQLite2:
    file: lib/Modwheel/DB/SQLite2.pm
    version: 0.3.3
  Modwheel::HTML::Tagset:
    file: lib/Modwheel/HTML/Tagset.pm
    version: 1.0.0
  Modwheel::Instance:
    file: lib/Modwheel/Instance.pm
    version: 0.3.3
  Modwheel::Object:
    file: lib/Modwheel/Object.pm
    version: 0.3.3
  Modwheel::REPL:
    file: lib/Modwheel/REPL.pm
    version: 0.3.3
  Modwheel::REPL::Prompt:
    file: lib/Modwheel/REPL/Prompt.pm
    version: 0.3.3
  Modwheel::Repository:
    file: lib/Modwheel/Repository.pm
    version: 0.3.3
  Modwheel::Session:
    file: lib/Modwheel/Session.pm
    version: 0.3.3
  Modwheel::Template:
    file: lib/Modwheel/Template.pm
    version: 0.3.3
  Modwheel::Template::ObjectProxy:
    file: lib/Modwheel/Template/ObjectProxy.pm
    version: 0.3.3
  Modwheel::Template::Shortcuts:
    file: lib/Modwheel/Template/Shortcuts.pm
    version: 0.3.3
  Modwheel::Template::TT:
    file: lib/Modwheel/Template/TT.pm
    version: 0.3.3
  Modwheel::Template::TT::Plugin:
    file: lib/Modwheel/Template/TT/Plugin.pm
    version: 0.3.3
  Modwheel::User:
    file: lib/Modwheel/User.pm
    version: 0.3.3
  Modwheel::User::Session:
    file: lib/Modwheel/User/Session.pm
    version: 0.3.3
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: Application
