# ####
# Modwheel configuration file for the modwheel test suite.
#
global:
  title: Modwheel
  defaultsite: Simple
  templatedir: /opt/modwheel/Templates/Simple
  directoryindex: index.html
  templatedriver: TT
  debug: 0
default:
  active: 1
  groupo: 100
  inherit: 1
  owner: 100
  parent: 1
  detach: 0
shortcuts:
  http: <a href="[type]:[content]">[name]</a>
  https: <a href="[type]:[content]">[name]</a>
  ftp: <a href="[type]:[content]">[name]</a>
  mail: <a href="mailto:[content]">[name]</a>
  cpan: <a href="http://search.cpan.org?query=[:content]&amp;mode=All">[name]</a>
  perldoc: <a href="http://perldoc.com/cgi-bin/htsearch?words=[:content]">[name]</a>
  google: <a href="http://google.startsiden.no/?q=[:content]">[name]</a> 
  cpanauthor: <a href="http://search.cpan.org/~[:content]">[name]</a>
site:
  Admin:
    database:
      name: modwheel
      host: localhost
      type: MySQL
      username: modwheel_user
      password: definityinfinity
    templatedir: /opt/modwheel/Templates/SimpleAdmin
    NeverDetach: Yes
    repository: /opt/modwheel/Repository
    repositoryurl: /rep
    templatedriver: TT
    directoryindex: index.html
    TT:
      plugins:
        Filter: Template::Plugin::Filter 
        CGI: Template::Plugin::CGI
        Date: Template::Plugin::Date
        URL: Template::Plugin::URL
    locale: en_EN
  Simple:
    database:
      name: modwheel
      host: localhost
      type: MySQL
      username: modwheel_user
      password: definityinfinity
    templatedir: /opt/modwheel/Templates/Simple
    repository: /opt/modwheel/Repository
    repositoryurl: /rep
    templatedriver: TT
    directoryindex: index.html
    TT:
      plugins:
        Filter: Template::Plugin::Filter 
        CGI: Template::Plugin::CGI
        Date: Template::Plugin::Date
        URL: Template::Plugin::URL
    locale: en_EN
