# ####
# Modwheel configuration file for the modwheel test suite.
#
global:
  title: Modwheel
  defaultsite: modwheeltest
  templatedir: /opt/devel/modwheel/Templates/
  directoryindex: index.html
  templatedriver: Bogus::Class
  debug: 1
default:
  detach: 0
  active: 1
  groupo: 100
  inherit: 1
  owner: 100
  parent: 1
shortcuts:
  http: <a href="[type]:[content]">[name]</a>
  https: <a href="[type]:[content]">[name]</a>
  ftp: <a href="[type]:[content]">[name]</a>
  mail: <a href="mailto:[content]">[name]</a>
  cpan: <a href="http://search.cpan.org?query=[:content]&amp;mode=All">[name]</a>
  perldoc: <a href="http://perldoc.com/cgi-bin/htsearch?words=[:content]">[name]</a>
  google: <a href="http://google.startsiden.no/?q=[:content]">[name]</a> 
  cpanauthor: <a href="http://search.cpan.org/~[:content]">[name]</a>
site:
  modwheeltest:
    database:
      name: modwheel
      host: localhost
      type: Bogus::Class
      username: modwheel
      password: torskd0rsk
    templatedir: /opt/devel/modwheel/Templates
    repository: /opt/devel/modwheel/Repository
    repositoryurl: /rep
    templatedriver: Bogus::Class
    directoryindex: index.html
    Bogus::Class:
      plugins:
        Filter: Template::Plugin::Filter 
        CGI: Template::Plugin::CGI
        Date: Template::Plugin::Date
        File: Template::Plugin::File
        HTML: Template::Plugin::HTML
        Image: Template::Plugin::Image
        Iterator: Template::Plugin::Iterator
        String: Template::Plugin::String
        URL: Template::Plugin::URL
        Wrap: Template::Plugin::Wrap
    uniqueidfortest: SITEID0001
  modwheeltest2:
    database:
      name: modwheel
      host: localhost
      type: 
      username: modwheel
      password: torskd0rsk
    templatedir: /opt/devel/modwheel/Templates
    templatedriver: Bogus::Class
    uniqueidfortest: SITEID0002
