# ####
# Modwheel configuration file for the modwheel test suite.
#
global:
  title: Modwheel
  defaultsite: modwheeltest
  templatedir: t/templates
  directoryindex: index.html
  templatedriver: TT
  TT:
    plugins:
      Filter: Template::Plugin::Filter
  debug: 1
  locale: no_NO
default:
  detach: 1
  active: 1
  groupo: 100
  inherit: 1
  owner: 100
  parent: 1
shortcuts:
  http: <a href="[type]://[content]">[name]</a>
  https: <a href="[type]://[content]">[name]</a>
  ftp: <a href="[type]://[content]">[name]</a>
  mail: <a href="mailto:[content]">[name]</a>
  cpan: <a href="http://search.cpan.org?query=[:content]&amp;mode=All">[name]</a>
  perldoc: <a href="http://perldoc.com/cgi-bin/htsearch?words=[:content]">[name]</a>
  google: <a href="http://google.startsiden.no/?q=[:content]">[name]</a> 
  cpanauthor: <a href="http://search.cpan.org/~[:content]">[name]</a>
  test: '<<[:type]>[type]<[:name]<[name]>[content]<[:content]>>'
site:
  modwheeltest:
    database:
      name: modwheel
      host: localhost
      type: MySQL
      username: modwheel
      password: torskd0rsk
    templatedir: t/templates
    repository: t/repository
    repositoryurl: /rep
    templatedriver: TT
    directoryindex: index.html
    TT:
      plugins:
        Filter: Template::Plugin::Filter 
        CGI: Template::Plugin::CGI
        Date: Template::Plugin::Date
        File: Template::Plugin::File
        HTML: Template::Plugin::HTML
        Image: Template::Plugin::Image
        Iterator: Template::Plugin::Iterator
        String: Template::Plugin::String
        URL: Template::Plugin::URL
        Wrap: Template::Plugin::Wrap
      COMPILE_DIR: t/cache/TT
    locale: en_EN
    uniqueidfortest: SITEID0001
  modwheeltest2:
    database:
      name: modwheel
      host: localhost
      type: MySQL
      username: modwheel
      password: torskd0rsk
    templatedir: t/templates/
    templatedriver: TT
    uniqueidfortest: SITEID0002
    TT:
      plugins: TEST_if_it_breaks_when_plugins_is_not_HASH
      INTERPOLATE: 1
      POST_CHOMP: 0
      RELATIVE: 0 
      ABSOLUTE: 0
  modwheeltest3:
    database:
      name: modwheel
      host: localhost
      type: MySQL
      username: modwheel
      password: torskd0rsk
    templatedir: t/templates/
    templatedriver: TT
    uniqueidfortest: SITEID0003
    TT:
      INTERPOLATE: 0
      POST_CHOMP: 1
      RELATIVE: 1
      ABSOLUTE: 1
